
services:
  akhq:
    # build:
    #   context: .
    image: tchiotludo/akhq
    network_mode: host
    container_name: kafka-akhq
    command: |
      java -Xmx512m -Xms512m 
           -Dfile.encoding=UTF-8 -Djava.awt.headless=true 
           -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heapdump.log 
           -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8686 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false 
           -jar /app/akhq.jar 
    environment:
      AKHQ_CONFIGURATION: |
        micronaut:
          server:
            port: 9080
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "localhost:9092,localhost:9192,localhost:9292"



      
  redpanda:
    image : docker.redpanda.com/redpandadata/console:latest
    container_name: kafka-redpanda
    network_mode: host
    environment:
      - KAFKA_BROKERS=localhost:9092,localhost:9192,localhost:9292




