
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    networks:
     - elk
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.1
    networks:
     - elk
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch

networks:
  elk:
