## Fichier de configuration SASL/OAUTHBEARER pour les outils d'admin Kafka
## Utilisé par setup-acls.sh → s'authentifie comme kafka-broker (super user)

security.protocol=SASL_PLAINTEXT
sasl.mechanism=OAUTHBEARER
sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
sasl.oauthbearer.token.endpoint.url=http://keycloak:9090/realms/kafka/protocol/openid-connect/token
sasl.oauthbearer.client.credentials.client.id=kafka-broker
sasl.oauthbearer.client.credentials.client.secret=broker-secret
sasl.oauthbearer.scope=openid
