services:
  consumer-postgresql:
    image: postgres:15.1
    volumes:
      - gateway_db:/var/lib/postgresql
      - gateway_data:/var/lib/postgresql/data
    networks:
      - back
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=consumer
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on:
      - consumer-postgresql
    networks:
      - back
volumes:
  gateway_data:
  gateway_db:

networks:
  back:

