spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql:consumer
    username: postgres
    password: postgres
  kafka:
    ssl:
      trust-store-location: file:///home/dthibau/Formations/Kafka/github/slides/TPs/9_securite/9.1_SSL/ssl/mount/kafka.truststore.jks
      trust-store-password: secret
    security:
      protocol: SASL_SSL
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="alice"
        password="alice-secret";
    consumer:
      group-id: consumer
      bootstrap-servers:
      - localhost:19092
      - localhost:19093
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.formation.model.JsonDeserializer


    listener:
      concurrency: 3




  jpa:
    hibernate:
      ddl-auto: update
#logging:
#  file:
#    name: consume.log
#    path: .