server:
  port: 8086
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console.enabled: false
    
  kafka:
    consumer:
      group-id: consumer
      bootstrap-servers:
      - localhost:9094
      - localhost:9194
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.formation.model.JsonDeserializer
      security:
        protocol: SASL_SSL
      ssl:
        trust-store-location: file:///home/dthibau/Formations/Kafka/github/kafka-admin-solutions/ssl/truststore/kafka.truststore.jks
        trust-store-password: secret
      properties:
        sasl:
          mechanism: PLAIN
          jaas:
            config: org.apache.kafka.common.security.plain.PlainLoginModule required username="alice" password="alice-secret";
    listener:
      concurrency: 3




#logging:
#  file:
#    name: consume.log
#    path: .