spring:
  cloud:
    stream:
      bindings:
        position-in-0:
          destination: position
# A compléter
  kafka:
    producer:
      acks: all
    consumer:
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092,
